### PR TITLE
fix event slug url matching

### PR DESCRIPTION
**Pull request by luto**
See #113 for details :)

Django does not seem to provide an easy way to match slugs within URLs. [The internet](https://stackoverflow.com/questions/31216363/url-pattern-for-alphanumericslug-string-in-django) [recommends](https://stackoverflow.com/questions/23358685/regular-expression-in-url-for-django-slug) to just use an regex for that. So I did. If you know a smarter way, just hit me up and I'll change this around.

The diff is kind of big, because I removed all the duplicate slug-matching from the URLs. This way I only had the replace the regex in three places.

### CODE REVIEW

**Comment by luto** [comment]
> Imports are incorrectly sorted.

I really need a commit hook for that.

**Comment by luto** [comment]
The failed pylama tests seem to be in `setup.py`, which is not touched by this PR.

**Comment by rixx** [comment]
Hmm, this PR allows dashes, but does not include dots.

How about adding a `SLUG_CHARS = 'a-zA-Z0-9.-'` to `events.models.event`, and using it both in the `urls.py`s and in the `RegexValidator` on an event's slug field?

**Comment by luto** [comment]
Sure, will do. :)

**Comment by luto** [comment]
@rixx please take another look :)

**Comment by rixx** [comment]
Thank you!

**Comment by luto** [comment]
42 open issues in the tracker, 42 open issues.
Assign one to me and merge it around, 41 open issues in the tracker! 🎶

**Pull request merged**
